{
 "title": "Team22 App Experiment Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Average latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(model_call_duration_seconds_sum[5m])) / sum(rate(model_call_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Model Request Histogram",
   "type": "heatmap",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (le) (rate(http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request latency percentiles (p50/p90/p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(model_call_duration_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(model_call_duration_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(model_call_duration_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_guess_counter", "legendFormat": "Total Succesfull Requests" },
    { "expr": "cached_guess_counter", "legendFormat": "Requests from Cache" }
   ]
  }
 ]
}