{{- if .Values.ratelimit.enable }}
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: global-ratelimit-rule # this is for deciding what to send to the rate limiting service and when it is applied
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: VIRTUAL_HOST
      match:
        context: GATEWAY
        routeConfiguration:
          vhost:
            name: "" # applying to all virtual hosts
            route:
              action: ANY
      patch:
        operation: MERGE
        value:
          rate_limits:
            - actions:
                - request_headers: # send the path to service
                    header_name: ":path"
                    descriptor_key: "PATH"
{{- end }}
