---
# Istio Gateway
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.global.ingressGatewayName }}
  namespace: istio-system
spec:
  selector:
    app: istio-ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "{{ .Values.global.stableSubdomain }}.{{ .Values.global.domain }}"
        - "{{ .Values.global.prereleaseSubdomain }}.{{ .Values.global.domain }}"
{{- if .Values.grafana.enabled }}
        - "{{ .Values.grafana.grafanaHost }}"
{{- end }}
