# Add Gateway
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.global.ingressGatewayName }}
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "{{ .Values.global.stableSubdomain }}.{{ .Values.global.domain }}"
        - "{{ .Values.global.prereleaseSubdomain }}.{{ .Values.global.domain }}"
---
# Add virtual service for app
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: app-virtualservice
spec:
  hosts:
    - "{{ .Values.global.stableSubdomain }}.{{ .Values.global.domain }}"
    - "{{ .Values.global.prereleaseSubdomain }}.{{ .Values.global.domain }}"
  gateways:
    - istio-system/{{ .Values.global.ingressGatewayName }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: app-svc
            subset: stable
          weight: {{ .Values.app.stableWeight }}
        - destination:
            host: app-svc
            subset: canary
          weight: {{ .Values.app.canaryWeight }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: modelservice-virtualservice
spec:
  hosts:
    - model-svc
  http:
    - route:
        - destination:
            host: model-svc
            subset: stable
          weight: {{ .Values.modelservice.stableWeight }}
        - destination:
            host: model-svc
            subset: canary
          weight: {{ .Values.modelservice.canaryWeight }}
---
# Add destination rule for app
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: app-dr
spec:
  host: app-svc
  subsets:
    - name: stable
      labels:
        version: stable
    - name: canary
      labels:
        version: canary
---
# Add destination rule for model-service
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: model-dr
spec:
  host: model-svc
  subsets:
    - name: stable
      labels:
        version: stable
    - name: canary
      labels:
        version: canary