# Add Gateway
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.global.ingressGatewayName }}
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "{{ .Values.global.stableSubdomain }}.{{ .Values.global.domain }}"
        - "{{ .Values.global.prereleaseSubdomain }}.{{ .Values.global.domain }}"
---
# Add virtual service
# https://faun.pub/consistent-hashing-and-httpmatch-route-with-istio-on-gke-https-redirect-8424b270184c 
# The sticky session is happening here, rather than the destination rule, it seems to be the only way that it works. while also doing the 90/10 routing. Im panning on talking to the teacher rq to double check this. 
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: app-virtualservice
spec:
  hosts:
    - "{{ .Values.global.stableSubdomain }}.{{ .Values.global.domain }}"
    - "{{ .Values.global.prereleaseSubdomain }}.{{ .Values.global.domain }}"
  gateways:
    - istio-system/{{ .Values.global.ingressGatewayName }}
  http:
    - match: 
      - headers: 
          x-session-id: 
            exact: stable 
      route: 
      - destination: 
          host: app-svc
          subset: stable
    - match: 
      - headers: 
          x-session-id: 
            exact: canary 
      route: 
      - destination: 
          host: app-svc 
          subset: canary
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: app-svc
            subset: stable
          weight: {{ .Values.app.stableWeight }}
        - destination:
            host: app-svc
            subset: canary
          weight: {{ .Values.app.canaryWeight }}
---
# Add destination rule
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: app-dr
spec:
  host: app-svc
  subsets:
    - name: stable
      labels:
        version: stable
    - name: canary
      labels:
        version: canary
