apiVersion: v1
kind: Service
metadata:
  name: modelservice
spec:
  type: ClusterIP
  selector:
    app: modelservice
  ports:
    - port: {{ .Values.modelservice.port }}
      targetPort: {{ .Values.modelservice.port }}